---
name: gradle-build-pipeline
description: "Checkout, build and tag gradle projects"
inputs:
  chart_name:
    description: "The name of the chart to deploy "
    required: true
  chart_version:
    description: "The version of the chart to deploy "
    required: true
  clean_up:
    description: "Tell Helm to clean up failed deployment. Disable only while debugging deployment issue."
    required: false
    default: "true"
  component_name:
    description: "The name of the component being deployed, it is the helm release name;
                  it also serves as the default base name for the kubernetes namespace."
    required: true
  dry_run:
    description: "Set to true to perform a helm dry-run deployment"
    required: false
    default: "false"
  github_token:
    description: "The authentication token"
    required: true
  helm_registry:
    description: "The registry to retrieve Helm charts from"
    required: true
  helm_value_command:
    description: "Name of a file providing a set of (action key value) for additional values to helm"
    required: false
    default: "src/main/helm/read-cloudFormation-values.cmd"
  locator_url:
    description: "The URL of properties file that defines aws_region, aws_role, cluster_name."
    required: false
    default: ""
  locator_url_bearer:
    description: "A authentication bearer with read access to locator_url."
    required: false
    default: ""
  locator_url_token:
    description: "An authentication token with read access to locator_url."
    required: false
    default: ""
  namespace:
    description: "The name of the namespace to deploy to."
    required: true
  post_install_parameter:
    description: "Name of a json file providing additional parameters for the post-install CloudFormation stacks"
    required: false
    default: ""
  pre_install_parameter:
    description: "Name of a json file providing additional parameters for the pre-install CloudFormation stacks"
    required: false
    default: ""
  purpose:
    description: "The purpose in the deployment pipeline (dev, prod, ...)"
    required: true
  timeout:
    description: "time to wait for the deployment to succeed (a Go duration, default 5m0s)"
    required: false
    default: "5m0s"
  verbose:
    description: "enable verbose output"
    required: false
    default: "false"
  workflow_dispatch_name:
    description: "The name of the post-deployment (test) workflow in the repository"
    required: false
    default: ""
  workflow_dispatch_ref:
    description: "The ref of the post-deployment (test) workflow in the repository"
    required: false
    default: ""
  workflow_dispatch_repository:
    description: "A repository with post-deployment behavior"
    required: false
    default: ""
  workflow_dispatch_token:
    description: "A GitHub token with workflow dispatch permission to trigger the post-deployment (test) workflow"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: "Mask secrets in logs"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u

        echo "::add-mask::${{ inputs.github_token }}"
        [ -n "${{ inputs.locator_url_bearer }}" ] && echo "::add-mask::${{ inputs.locator_url_bearer }}"
        [ -n "${{ inputs.locator_url_token }}" ] && echo "::add-mask::${{ inputs.locator_url_token }}"
    - name: "Extract purpose configuration"
      id: purpose_config
      uses: Arda-cards/purpose-configuration-action@v1
      with:
        locator_url: "${{ inputs.locator_url }}"
        locator_url_token: "${{ inputs.locator_url_token }}"
    - uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: "${{ steps.purpose_config.outputs.aws_role }}"
        aws-region: "${{ steps.purpose_config.outputs.aws_region }}"
        role-duration-seconds: 900
    - name: "Extract account information"
      id: account_information
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u

        readonly name=$(aws --query AccountName --output text account get-account-information)
        echo "name=${name}" >>"${GITHUB_OUTPUT}"
    - name: "Add default CloudFormation Parameters"
      id: cloudformation_parameter
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u

        maybeAppend() {
          echo "maybeAppend ${2} to ${1}"
          mv "${1}" in.json
          jq --arg key "${2}" --arg value "${3}" \
            'if
              map(.ParameterKey) | index($key) == null
            then
              . + [{"ParameterKey": $key, "ParameterValue": $value}]
            else
              .
            end' in.json > "${1}"
          rm in.json
        }
        
        standard_parameters() {
          if [ -z "${1}" ]; then
            file_name="${{ runner.temp }}/${2}.json"
            echo '[]' > "${file_name}"
          else
            file_name="$(realpath "${1}")"
          fi
          echo "${2}=file:///${file_name}" >>"${GITHUB_OUTPUT}"

          maybeAppend "${file_name}" "Component" "${{ inputs.component_name }}"
          maybeAppend "${file_name}" "Infrastructure" "${{ steps.account_information.outputs.name }}"
          maybeAppend "${file_name}" "Namespace" "${{ inputs.namespace }}"
          maybeAppend "${file_name}" "Purpose" "${{ inputs.purpose }}"
        }

        standard_parameters "${{ inputs.pre_install_parameter }}" pre_install_parameter
        standard_parameters "${{ inputs.post_install_parameter }}" post_install_parameter
    - name: "Pre-install cloudformation"
      uses: aws-actions/aws-cloudformation-github-deploy@v2
      if: ${{ hashFiles('src/main/cloudformation/pre-install.cfn.yml') != '' }}
      with:
        capabilities: "CAPABILITY_NAMED_IAM"
        mode: ${{ inputs.dry_run == 'false' && 'create-and-execute' || 'create-only' }}
        name: "${{ steps.account_information.outputs.name }}-${{ inputs.namespace }}-pre"
        parameter-overrides: "${{ steps.cloudformation_parameter.outputs.pre_install_parameter }}"
        tags: "[ { \"Key\":\"Infrastructure\", \"Value\":\"${{ steps.account_information.outputs.name }}\" } ]"
        template: "src/main/cloudformation/pre-install.cfn.yml"
    - name: "Parametrize Helm values from CloudFormationExports"
      id: helm_value
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u

        function readExport {
          local value="$(aws cloudformation list-exports --query "Exports[?Name=='${{ steps.account_information.outputs.name }}-${2}'].Value" --output text)"
          if [ -z "${value}" ]; then
            echo "::error::CloudFormation export ${{ steps.account_information.outputs.name }}-${2} not found or empty"
            exit 1
          fi
          yq -i "${1} = \"${value}\"" "${3}"
        }

        # ARN for secret name:
        # arn:aws:secretsmanager:${region}:${account}:secret:${secret_name}-${version}
        function readSecretName {
          local value="$(aws cloudformation list-exports --query "Exports[?Name=='${{ steps.account_information.outputs.name }}-${2}'].Value" --output text)"
          if [ -z "${value}" ]; then
            echo "::error::CloudFormation export ${{ steps.account_information.outputs.name }}-${2} not found or empty"
            exit 1
          fi
          local secret_long_name=${value##*:secret:}
          yq -i "${1} =\"${secret_long_name%-*}\"" "${3}"
        }

        file_name="${{ runner.temp }}/cloudFormation-values.yaml"
        echo "file_name=${file_name}" >>${GITHUB_OUTPUT}
        echo "---" >|${file_name}
        yq -i ".global.infrastructure = \"${{ steps.account_information.outputs.name }}\"" ${file_name}
        yq -i ".global.infrastructure = \"${{ steps.account_information.outputs.name }}\"" ${file_name}
        yq -i ".global.infrastructure = \"${{ steps.account_information.outputs.name }}\"" ${file_name}

        if [[ -f ${{ inputs.helm_value_command }} && -r ${{ inputs.helm_value_command }} ]]; then
          # read file line by line and write command to set *Key* to *Action* *Value*.   Field separator is ":"

          COMPONENT="${{ inputs.component_name }}" \
          INFRASTRUCTURE="${{ steps.account_information.outputs.name }}" \
          NAMESPACE="${{ inputs.namespace }}" \
          PURPOSE="${{ inputs.purpose }}" \
          envsubst '${COMPONENT} ${INFRASTRUCTURE} ${NAMESPACE} ${PURPOSE}' <"${{ inputs.helm_value_command }}" |
          while read -r a k v; do
            case $a in
              copyValue)
                yq -i "${k} = \"${v}\"" ${file_name}
              ;;
              readExport)
                readExport $k $v ${file_name}
              ;;
              readSecretName)
                readSecretName $k $v ${file_name}
              ;;
              *)
                echo "::error::function $a unknown (readExport, readSecretName)"
                exit 1
              ;;
            esac
          done

          echo "${file_name}:"
          cat "${file_name}"
        fi
    - name: "Deploying ${{ inputs.chart_name }}:${{ inputs.chart_version }} for ${{ inputs.purpose }}"
      shell: bash
      run: |
        if [ "${{ runner.debug }}" == 1 ]; then
          set -xv
          readonly verbose=true
        elif [ "${{ inputs.verbose }}" = "true" ]; then
          readonly verbose=true
        fi
        set -u
        
        [ "${verbose:-false}" = "true" ] && aws sts get-caller-identity
        
        aws eks --region "${{ steps.purpose_config.outputs.aws_region }}" update-kubeconfig --name "${{ steps.purpose_config.outputs.cluster_name }}"
        
        echo "${{ inputs.github_token }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
        
        echo "🚀🚀🚀 Upgrading ${{ inputs.purpose }} in ${{ steps.purpose_config.outputs.cluster_name }} 🚀🚀🚀"
        echo "${{ inputs.chart_name }}:${{ inputs.chart_version }}"
        echo "🚀🚀🚀 ==================== 🚀🚀🚀"
        
        options=()
        if [ "${{ inputs.clean_up }}" = "true" ]; then
          options+=("--atomic" "--cleanup-on-fail")
        else
          options+=("--wait")
        fi
        if [ "${{ inputs.dry_run }}" = "true" ]; then
          echo "🟧🟧🟧 dry run 🟧🟧🟧"
          options+=("--dry-run")
        fi
        [ "${{ inputs.verbose }}" = "true" ] && options+=("--debug")
        
        values=("--values" "src/main/helm/values-${{ inputs.purpose }}.yaml")
        [ -n "${{ steps.helm_value.outputs.file_name }}" ] && [ -r "${{ steps.helm_value.outputs.file_name }}" ] && values+=("--values" "${{ steps.helm_value.outputs.file_name }}")
        
        helm upgrade --install --render-subchart-notes \
          "${options[@]}" \
          --version "${{ inputs.chart_version }}" \
          --create-namespace --namespace "${{ inputs.namespace }}" \
          --timeout "${{ inputs.timeout }}" \
          "${values[@]}" \
          --set "global.awsRegion=${{ steps.purpose_config.outputs.aws_region }}" \
          --set "global.purpose=${{ inputs.purpose }}" \
          "${{ inputs.component_name }}" "${{ inputs.helm_registry }}/${{ inputs.chart_name }}"
    - name: "Post-install cloudformation"
      uses: aws-actions/aws-cloudformation-github-deploy@v2
      if: ${{ hashFiles('src/main/cloudformation/post-install.cfn.yml') != '' }}
      with:
        mode: ${{ inputs.dry_run == 'false' && 'create-and-execute' || 'create-only' }}
        name: "${{ steps.account_information.outputs.name }}-${{ inputs.namespace }}-post"
        parameter-overrides: "${{ steps.cloudformation_parameter.outputs.post_install_parameter }}"
        tags: "[ { \"Key\":\"Infrastructure\", \"Value\":\"${{ steps.account_information.outputs.name }}\" } ]"
        template: "src/main/cloudformation/post-install.cfn.yml"
    - name: Trigger post-deployment test
      if: ${{ inputs.workflow_dispatch_name && inputs.workflow_dispatch_ref && inputs.workflow_dispatch_repository && inputs.workflow_dispatch_token }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.workflow_dispatch_token }}
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u

        run_url="$(
          gh workflow run ${{ inputs.workflow_dispatch_name }} \
          --repo ${{ inputs.workflow_dispatch_repository }} \
          --ref ${{ inputs.workflow_dispatch_ref }}  \
          -f includedTags=${{ inputs.component_name }},${{ inputs.purpose }} \
          -f ${{ inputs.component_name }}_target_version=${{ inputs.chart_version }}
        )"
        
        echo "::notice title=Triggered test workflow::$run_url"
        
        run_id="${run_url##*/}"
        
        if [[ -z "$run_id" || "$run_id" == "$run_url" ]]; then
          echo "::error::Failed to extract run ID from workflow URL: $run_url" >&2
          exit 1
        fi
        
        echo "Ignore 'requesting annotations returned 403 Forbidden'"
        echo "it is a limitation of fine-grained tokens when used with the gh cli."
        gh run watch "$run_id" --repo ${{ inputs.workflow_dispatch_repository }} --exit-status
        echo "Ignore 'requesting annotations returned 403 Forbidden'"
        echo "it is a limitation of fine-grained tokens when used with the gh cli."
        echo "::notice title=Test workflow::$run_url completed"
